#!/bin/bash
# Duck Dive Sales Report — Daily Automated Send
# Usage: send-report.sh [--day-type weekday|sunday|monthend]

DAY_TYPE="${1:-weekday}"
REPO_DIR="/home/node/.openclaw/workspace/projects/duck-dive/sales-reports"
REPORT_DIR="$REPO_DIR/reports"

RECIPIENTS="daniele.scaglia@womix.io"
# RECIPIENTS_FULL="daniele.scaglia@womix.io,giuseppe.langella@duckdivegin.com,mella.federico@gmail.com,marco.biasibetti@gmail.com"

# Generate report
echo "📊 Generating report..."
cd "$REPO_DIR"
node daily-kpi-report.js --output-dir "$REPORT_DIR" 2>&1 | head -5

if [ ! -f "$REPORT_DIR/latest.html" ]; then
  echo "❌ Report generation failed"
  exit 1
fi

# Read metadata
META=$(cat "$REPORT_DIR/latest-meta.json")
SUBJECT=$(echo "$META" | jq -r '.subject')

# Send the HTML generated by daily-kpi-report.js directly
echo "📧 Sending to team..."
EMAIL_BODY=$(cat "$REPORT_DIR/latest.html")
gog gmail send \
  --account eva@womix.io \
  --to "$RECIPIENTS" \
  --subject "$SUBJECT" \
  --body-html "$EMAIL_BODY" \
  -y > /dev/null 2>&1

if [ $? -eq 0 ]; then
  echo "✅ Report sent successfully!"
  echo "   Recipients: $RECIPIENTS"
  echo "   Day type: $DAY_TYPE"
else
  echo "❌ Failed to send report"
  exit 1
fi

exit 0

# ---- LEGACY TEMPLATE (kept for reference) ----
# Build considerations based on day type
case "$DAY_TYPE" in
  weekday)
    CONSIDERATIONS="<p><strong>📈 Trend:</strong> Monitorare i numeri di questa settimana. Report completo domenica mattina.</p>"
    ;;
  sunday)
    CONSIDERATIONS="<div class='section'><h3>📊 Sunto Settimanale</h3><p>Analisi dettagliata dell'andamento della settimana appena conclusa. Confronto con target e identificazione delle aree di miglioramento.</p><p><strong>Fatturato:</strong> Monitorare trend e canali. <strong>Conversioni:</strong> Verificare performance per agente. <strong>Opportunities:</strong> Identificare quick wins per la settimana prossima.</p></div>"
    ;;
  monthend)
    CONSIDERATIONS="<div class='section'><h3>📋 Riassunto Mensile</h3><p><strong>Performance Complessiva:</strong> Analisi totale del mese. Target raggiunto? Quali metriche hanno sovraperformato e quali hanno deluso?</p><p><strong>Agenti:</strong> Ranking performance. Chi ha portato fatturato? Chi ha più visite ma meno conversioni?</p><p><strong>Canali:</strong> Quale canale ha trainato il mese? Concentrazione di rischio? Mix consigliato per il prossimo mese.</p><p><strong>Action Items:</strong> Cosa cambiare per il prossimo mese? Investimenti? Focus su specifici agenti/canali?</p></div>"
    ;;
esac

# Build email HTML
read -r -d '' EMAIL_BODY << 'EOF'
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f5f5f5; margin: 0; padding: 20px; }
        .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
        .header { background: linear-gradient(135deg, #1e1b4b, #312e81); color: white; padding: 30px 20px; text-align: center; }
        .header h1 { margin: 0; font-size: 24px; font-weight: 800; }
        .header p { margin: 8px 0 0 0; font-size: 14px; opacity: 0.9; }
        .content { padding: 30px 20px; }
        .cta-button { display: inline-block; background: #4f46e5; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 600; margin: 20px 0; }
        .cta-button:hover { background: #4338ca; }
        .section { margin: 25px 0; padding: 20px; background: #f8f9fa; border-radius: 6px; border-left: 4px solid #4f46e5; }
        .section h3 { margin: 0 0 10px 0; color: #1e293b; font-size: 16px; }
        .section p { margin: 5px 0; color: #475569; font-size: 14px; line-height: 1.6; }
        .kpi-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 15px 0; }
        .kpi-item { padding: 12px; background: white; border-radius: 4px; border-left: 3px solid #059669; }
        .kpi-label { font-size: 12px; color: #64748b; text-transform: uppercase; }
        .kpi-value { font-size: 18px; font-weight: 700; color: #1e293b; margin-top: 5px; }
        .footer { background: #f1f5f9; padding: 20px; text-align: center; font-size: 12px; color: #64748b; }
        .footer a { color: #4f46e5; text-decoration: none; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📊 Duck Dive Sales Report</h1>
            <p id="subtitle"></p>
        </div>

        <div class="content">
            <p>Buongiorno Team,</p>

            <p>Il report è pronto. <strong>Vedi i dettagli</strong>:</p>

            <center>
                <a href="https://duck-dive-report.surge.sh/" class="cta-button">
                    📈 Visualizza Report Completo
                </a>
            </center>

            <div id="considerations"></div>

            <p>Grazie,<br><strong>Eva</strong> 🌿</p>
        </div>

        <div class="footer">
            <p>Report automatico generato da Duck Dive Sales Report</p>
        </div>
    </div>
</body>
</html>
EOF

# Replace placeholders
EMAIL_BODY="${EMAIL_BODY//'<p id="subtitle"></p>'/"<p>$(date '+%A %d %B %Y')</p>"}"
EMAIL_BODY="${EMAIL_BODY//'<div id="considerations"></div>'/"$CONSIDERATIONS"}"

# Send via gog
echo "📧 Sending to team..."
gog gmail send \
  --account eva@womix.io \
  --to "$RECIPIENTS" \
  --subject "$SUBJECT" \
  --body-html "$EMAIL_BODY" \
  -y > /dev/null 2>&1

if [ $? -eq 0 ]; then
  echo "✅ Report sent successfully!"
  echo "   Recipients: $RECIPIENTS"
  echo "   Day type: $DAY_TYPE"
else
  echo "❌ Failed to send report"
  exit 1
fi
